apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: he8kh0u9r-dotnet-basic 
  janus-idp.io/tekton: he8kh0u9r-dotnet-basic
  backstage.io/kubernetes-id: he8kh0u9r-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: he8kh0u9r-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml